version: '3.8'

services:
  # Database Service
  db:
    image: mysql:8.0
    container_name: taskmanagement_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: taskmanagement_db
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: taskpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - taskmanagement_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  # Application Service
  app:
    build: .
    container_name: taskmanagement_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_USERNAME: taskuser
      DB_PASSWORD: taskpass
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/taskmanagement_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - app_logs:/var/log/taskmanagement
    networks:
      - taskmanagement_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: taskmanagement_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/certs
    depends_on:
      - app
    networks:
      - taskmanagement_network

volumes:
  db_data:
    driver: local
  app_logs:
    driver: local

networks:
  taskmanagement_network:
    driver: bridge
